#!/usr/bin/env python3
"""
Quick Setup Script for Satellite Hub Authentication System
Run: python setup_auth.py
"""

import os
import sys
import subprocess
from pathlib import Path

def print_header(text):
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")

def run_command(cmd, description):
    print(f"📦 {description}...")
    try:
        result = subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)
        print(f"✅ {description} - Success!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ {description} - Failed!")
        print(f"Error: {e.stderr}")
        return False

def create_env_file():
    print_header("Setting Up Environment Variables")
    
    env_path = Path(".env")
    if env_path.exists():
        print("⚠️  .env file already exists. Skipping...")
        return
    
    secret_key = os.urandom(16).hex()
    
    env_content = f"""# Satellite Hub Configuration
# Generated by setup_auth.py

# Flask Configuration
SECRET_KEY={secret_key}
FLASK_ENV=development
DEBUG=True

# Database Configuration
DATABASE_URL=sqlite:///satellite.db

# Optional: Payment Gateway (add if using Stripe/PayPal)
# STRIPE_SECRET_KEY=your_stripe_key
# STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key
# PAYPAL_CLIENT_ID=your_paypal_client_id
# PAYPAL_CLIENT_SECRET=your_paypal_client_secret

# Optional: Email Notifications
# MAIL_SERVER=smtp.gmail.com
# MAIL_PORT=587
# MAIL_USE_TLS=True
# MAIL_USERNAME=your_email
# MAIL_PASSWORD=your_password
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✅ Created .env file with secret key")
    print(f"📝 SECRET_KEY: {secret_key}")

def check_directories():
    print_header("Creating Necessary Directories")
    
    directories = [
        'templates/auth',
        'static',
        'logs'
    ]
    
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
        print(f"✅ {directory}/ exists")

def initialize_database():
    print_header("Initializing Database")
    
    try:
        from app import app, db
        from models import User, Subscription, Transaction
        
        with app.app_context():
            db.create_all()
            
            # Check if subscriptions already exist
            if Subscription.query.count() == 0:
                print("📝 Creating default subscription plans...")
                
                basic = Subscription(
                    name='basic',
                    price=9.99,
                    duration_days=30,
                    features=['Advanced NDVI & SMI analysis', 'Up to 3 AOI areas', '100x daily requests', 'High resolution imagery', 'Priority support', 'Monthly reports']
                )
                premium = Subscription(
                    name='premium',
                    price=29.99,
                    duration_days=30,
                    features=['Full analysis suite', 'Unlimited AOI areas', 'Unlimited daily requests', 'Maximum resolution imagery', '24/7 dedicated support', 'Advanced API access', 'Custom reports & exports', 'ML-powered predictions']
                )
                db.session.add(basic)
                db.session.add(premium)
                db.session.commit()
                
                print("✅ Basic Plan: $9.99/month")
                print("✅ Premium Plan: $29.99/month")
            else:
                print("ℹ️  Subscription plans already exist")
            
            print("✅ Database initialized successfully")
            print(f"📁 Database file: satellite.db")
        
        return True
    except Exception as e:
        print(f"❌ Database initialization failed: {e}")
        return False

def create_test_user():
    print_header("Creating Test User (Optional)")
    
    response = input("Create a test account? (y/n): ").strip().lower()
    
    if response != 'y':
        print("Skipping test user creation")
        return
    
    try:
        from app import app, db
        from models import User
        
        email = input("Email: ").strip()
        username = input("Username: ").strip()
        password = input("Password: ").strip()
        
        with app.app_context():
            # Check if user exists
            if User.query.filter_by(email=email).first():
                print(f"❌ User with email {email} already exists")
                return
            
            user = User(
                email=email,
                username=username,
                subscription_type='trial',
                trial_days=10
            )
            user.set_password(password)
            db.session.add(user)
            db.session.commit()
            
            print(f"\n✅ Test user created successfully!")
            print(f"📧 Email: {email}")
            print(f"👤 Username: {username}")
            print(f"🎁 Trial Days: 10")
            print(f"🔐 Login at: http://localhost:5000/auth/login")
    
    except Exception as e:
        print(f"❌ Failed to create test user: {e}")

def main():
    print_header("🛰️  Satellite Hub - Authentication System Setup")
    
    print("""
This script will set up your authentication system with:
  ✓ User database (SQLite)
  ✓ Email/password authentication
  ✓ 10-day free trial tracking
  ✓ Subscription management
  ✓ Role-based access control
    """)
    
    # Step 1: Check directories
    check_directories()
    
    # Step 2: Create .env file
    create_env_file()
    
    # Step 3: Install requirements
    print_header("Installing Dependencies")
    if run_command("pip install -r requirements_auth.txt", "Installing authentication dependencies"):
        print("✅ All dependencies installed")
    else:
        print("⚠️  Some dependencies failed to install")
        sys.exit(1)
    
    # Step 4: Initialize database
    if initialize_database():
        print("✅ Database setup complete")
    else:
        print("⚠️  Database setup encountered issues")
    
    # Step 5: Create test user
    create_test_user()
    
    # Final instructions
    print_header("✅ Setup Complete!")
    
    print("""
Next Steps:
  1. Start the Flask app:
     python app.py
  
  2. Open browser:
     http://localhost:5000/
  
  3. You'll be redirected to login page
     - Sign up for new account (get 10-day trial)
     - Or login with test account
  
  4. Dashboard shows subscription status and countdown

Important:
  📁 Database: satellite.db (SQLite)
  🔐 Secret Key: Stored in .env file
  📝 Configuration: Update .env for production
  
Documentation:
  📖 Read AUTH_SETUP.md for detailed information
  📋 Check models.py for database schema
  🔌 See auth.py for authentication logic

Production Checklist:
  ☐ Generate strong SECRET_KEY
  ☐ Set FLASK_ENV=production
  ☐ Use PostgreSQL instead of SQLite
  ☐ Enable HTTPS/SSL
  ☐ Set up email notifications
  ☐ Integrate payment gateway (Stripe/PayPal)
  ☐ Add rate limiting
  ☐ Set up error logging
    """)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Setup failed with error: {e}")
        sys.exit(1)
